### ISSUE TITLE
OSM Place Search doesn't work in QGIS 3.6.0

### ISSUE THREAD

**Issue by RolfBerlin** [xcaeag/Nominatim-Qgis-Plugin#10]

**Comment by RolfBerlin** [comment]
Thats a pity, cause I use it every day several times. 
Thx in advance for fixing it!
Rolf

**Comment by xcaeag** [comment]
It's true !
the fix is comming...

**Comment by RolfBerlin** [comment]
It works! 
Thanks a lot! 
You saved my day ... month ... year ... :-)
Rolf
