### ISSUE TITLE
projection issue with qgis 3.8/proj 6

### ISSUE THREAD

**Issue by landryb** [xcaeag/Nominatim-Qgis-Plugin#11]
using the plugin since a while without issues, and since i upgraded to proj 6 the plugin behaves weird, ie with my map set to EPSG:2154 if i search for 'nantua' (in ain dept, france) it will relocate me to 6389160,3295272 which is somewhere in somalia, if i do the reverse search.

If i click on the reverse search result (cabudwaadq, galgaduud, somalia) then the map is centered on nantua.

I suspect this has something to do with proj6..

**Comment by landryb** [comment]
oh, and this is with version 1.2.6 of the plugin

**Comment by xcaeag** [comment]
I dont even know how to test proj6, also check/upgrade the version !

**Comment by xcaeag** [comment]
Works in QGis 3.9, with proj 5.2
How do you test proj 6?

**Comment by landryb** [comment]
I have an os (OpenBSD) where proj 6 replaced 5.2 in the packages.

**Comment by RAFALCO** [comment]
bonjour,
avec qgis 3.10.0.3 il y a proj: 6.2.1-1 d'installé. (et gdal 3)
l'erreur de projection reste la même que pour "landryb".

**Comment by xcaeag** [comment]
Une version 1.2.7 à tester très bientôt, elle fonctionne sur ma 3.10.
La transformation 'ogr' qui était effectuée est remplacée par les méthodes qu'offre PyQgis.

**Comment by landryb** [comment]
Merci beaucoup, je viens de faire le test depuis master avec ce dernier commit et ca fonctionne effectivement correctement.

**Comment by xcaeag** [comment]
Bien, merci de votre vigilance !
