### ISSUE TITLE
Use OSM-ID instead of Nominatim's internal place_id as ID

### ISSUE THREAD

**Issue by kannes** [xcaeag/Nominatim-Qgis-Plugin#13]
This is a feature request, not a bug report :)

The ID stored for the objects is the item's `place_id` which seems to be an internal detail of each Nominatim service. For the user it would probably be much more convenient to get the object's OSM-ID.

E. g. if the Tower of London was selected, the ID would be 370870741 (https://www.openstreetmap.org/way/370870741)

References:
- https://help.openstreetmap.org/questions/21542/nominatim-place-id
- https://help.openstreetmap.org/questions/37714/query-place_id

**Comment by xcaeag** [comment]
that's a good remark,
I'll take a look. 

Thanks

**Comment by kannes** [comment]
I will probably send a PR end of May for this and also for storing all the attributes as hstore string (like when you load a OSM PBF file) so users can get all the data available in OSM for the objects :)

**Comment by xcaeag** [comment]
ok, you are welcome !
