### ISSUE TITLE
The dock widget is not removed from the main window at plugin unload

### ISSUE THREAD

**Issue by borysiasty** [xcaeag/Nominatim-Qgis-Plugin#19]
Hi,

Referring to the issue described here:
https://github.com/borysiasty/plugin_reloader/issues/9#issuecomment-1386277718

it turned out the Nominatim's dockwidget is not removed from main window at plugin unload. Regardless of the described difference between plugin manager and reloader, it continues working even after disabling in the plugin manager.  

I guess it just misses:
```
self.dockwidget.deleteLater()
```

**Comment by xcaeag** [comment]
I admit I get a little lost in the mechanics of loading, unloading plugins.
Moving the dock initialization back into the "init" and using the "deleteLater()" as suggested, it looks better.
A release is coming for testing !
thank you.
