### ISSUE TITLE
Error when opening configuration

### ISSUE THREAD

**Issue by leonmvd** [xcaeag/Nominatim-Qgis-Plugin#2]
When opening the configuration from the plugin menu on Mac:

> An error has occurred while executing Python code: 
> 
> AttributeError: 'QDialogButtonBox' object has no attribute 'released' 
> Traceback (most recent call last):
>   File "/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/nominatim/nominatim.py", line 144, in do_config
>     dlg = nominatim_conf_dlg(self.iface.mainWindow(), self)
>   File "/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/nominatim/nominatim_conf_dlg.py", line 18, in __init__
>     self.buttonBox.released.connect(self.onExBox)
> AttributeError: 'QDialogButtonBox' object has no attribute 'released'
> 
> 
> Python version: 3.6.3 (default, Oct  4 2017, 06:09:15) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] 
> QGIS version: 2.99.0-Master Master, 3c7f745424

**Comment by xcaeag** [comment]
Effectively, a corrected version will be available after approval ...

thank you
