### ISSUE TITLE
Qgis 3 windows launch problem - Qvariant

### ISSUE THREAD

**Issue by alexmodesto73** [xcaeag/Nominatim-Qgis-Plugin#3]
Error 

Impossible de charger l'extension 'nominatim' provoque une erreur lors de l'appel à sa méthode classFactory()

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
 File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
   plugins[packageName] = package.classFactory(iface)
 File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\nominatim\__init__.py", line 27, in classFactory
   return nominatim(iface)
 File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\nominatim\nominatim.py", line 53, in __init__
   self.myLocale = locale[0:2]
TypeError: 'QVariant' object is not subscriptable

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.0-Girona Girona, 001c80b0c3

Chemin Python :
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/USER/Desktop
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res

**Comment by xcaeag** [comment]
Bonjour,

je n'arrive pas à reproduire le pb, dans un environnement qui semble similaire.
pouvez-vous réessayer en désinstallant, réinstallant... ?

merci

**Comment by alexmodesto73** [comment]
Il fonctionne désormais, on peut fermer l'issue :)

---
Alexandre MODESTO


2018-03-05 11:51 GMT+01:00 Xavier Culos <notifications@github.com>:
