### ISSUE TITLE
QGIS3: object located at wrong position

### ISSUE THREAD

**Issue by tobwen** [xcaeag/Nominatim-Qgis-Plugin#5]
When loading an object with a different default CRS than 3857, the object is located at a wrong position. This behaviour only happens, if nothing else has been loaded before. It works as expected when switching to EPSG:3857 before.

0. I'm on latest QGIS3 (release dev)
1. I've set EPSG:25832 as my default CRS.
2. I'm using "OSM place search" to find a place, f.e. "Essen" in Germany.
3. I'm adding the object to the map without having anything loaded before.
4. I'm selecting EPSG:3857 as CRS (same behaviour for EPSG:4326)
5. The object loaded is located at the wrong location.

Could you remove step 5? OSM only has one CRS (actually 4326) and this might confused users.

**Comment by baumsicht** [comment]
Similar issue with QGIS 3.4.13 64bit (but not on all devices). Object is located wrong in Africa. Is there a possibility to set the CRS?

**Comment by xcaeag** [comment]
Effectively,
the problem is fixed (to be tested) in version 3.6 of QGis.
you do not have the possibility to change version ?

**Comment by Sven315** [comment]
Same problem. We cant change the version, 3.4.15 is the LTR Version for our Company.

**Comment by xcaeag** [comment]
A few lines of code requires version 3.6. It's difficult to maintain two diverging versions ...
Loading a first blank project by default is perhaps a solution?
