### ISSUE TITLE
query has nothing in QGIS 2.18 

### ISSUE THREAD

**Issue by DFreeMind** [xcaeag/Nominatim-Qgis-Plugin#6]
I use this plugin in QGIS 2.18 , but when I query some location nothing return . Log Messages Panel has something as follow:

> 2018-07-11T17:04:43	1	http://nominatim.openstreetmap.org/search?format=json&q=london&addressdetails=0&polygon_text=1
> 2018-07-11T17:04:44	1	expected string or buffer

**Comment by xcaeag** [comment]
A new version has just been published, I hope it corrects the problem.

**Comment by RAFALCO** [comment]
this plugin seems to not work if there is a proxy with username and password. (qgis 3.2)
