### ISSUE TITLE
Cursor as spinning wheel

### ISSUE THREAD

**Issue by magerlin** [xcaeag/Nominatim-Qgis-Plugin#9]
When I have the plugin installed in Qgis 3, my cursor is shown as a spinning wheel already from when Qgis starts to load plugins. Removing the plugin makes Qgis show the normal cursors again.

**Comment by kannes** [comment]
Does this still happen for you?

**Comment by magerlin** [comment]
No 😉

Kind regards
Morten Agerlin Petersen
Senior Transport Planner, GIS and Data Analysis Specialist
M +45 51613615
***@***.******@***.***>
Rambøll Danmark A/S, CVR NR. 35128417
Hjemsted: Hannemanns Allé 53, 2300 København S

**Comment by kannes** [comment]
Excellent, thanks for the swift reply :)

**Comment by xcaeag** [comment]
The problem no longer exists?
The plugin has since been modified, maybe an old problem? I don't see where it could come from. 
Can I close this issue ?

**Comment by magerlin** [comment]
Yes, Close it 👍

Best regards/Med venlig hilsen

Morten Agerlin Petersen

________________________________
